  
import { images } from "./imagesFallback";

export type MenuItem = {
  id: string | number;
  nom: string;
  prix: string | { label: string; value: string; selected?: boolean }[];
  image: string | any;
  description?: string;
  catégorie: string[];
  filtre: string[];   //  Nouveau champ obligatoire (identique à catégorie)
  quantité?: number;
  masque?: boolean;   // Nouveau champ pour masquer l'item du menu
};

export const menuItems: MenuItem[] = [
  {
    id: 1,
    nom: "Poulet DG",
    prix: "4000 FCFA",
    image: '/poulet_DG.jpg',
    description: "Poulet frit mijoté avec plantains mûrs, légumes et épices.",
    catégorie: ["Plats principaux", "Plats chaud"],
    filtre: ["Plats principaux", "Plats chaud"],
  },
  {
    id: 2,
    nom: "Pomme sauté à la viande de boeuf",
    prix: "3000 FCFA",
    image: images.pommeViande,
    description: "Pommes de terre sautées accompagnées de viande de boeuf.",
    catégorie: ["Plats principaux", "Plats chaud"],
    filtre: ["Plats principaux", "Plats chaud"],
  },
  {
    id: 3,
    nom: "Poulet Braisé",
    prix: "4000 FCFA",
    image: images.pouletBraisé,
    description: "Poulet mariné et grillé au feu de bois, tendre et savoureux.",
    catégorie: ["Grillades & Poêlés", "Plats chaud"],
    filtre: ["Grillades & Poêlés", "Plats chaud"],
  },
  {
    id: 25,
    nom: "Poulet panné",
    prix: "4000 FCFA",
    image: images.pané,
    description: "Morceaux de poulet enrobé de chapelure et frit à la perfection.",
    catégorie: ["Grillades & Poêlés", "Plats chaud"],
    filtre: ["Grillades & Poêlés", "Plats chaud"],
  },
  {
    id: 4,
    nom: "Taro Sauce Jaune",
    prix: "2500 FCFA",
    image: images.taro,
    description: "Taro pilé accompagné d'une sauce jaune aux épices et huile de palme.Plat traditionnel Bamiléké très prisé disponible tout les dimanches",
    catégorie: ["Plats principaux", "Spécialitées du dimanche", "Plats traditionnels"],
    filtre: ["Plats principaux", "Spécialitées du dimanche", "Plats traditionnels"],
  },
  {
    id: 5,
    nom: "Eru",
    prix: "2500 FCFA",
    image: images.eru,
    description: "Plat traditionnel à base de feuilles d'okok et waterleaf finement coupées, mijotées avec de l’eau, du poisson fumé, de la viande, le tout relevé avec un peu d’huile R, disponible le dimanche.",
    catégorie: ["Spécialitées du dimanche", "Plats chaud", "Plats traditionnels", "Plats principaux"],
    filtre: ["Spécialitées du dimanche", "Plats chaud", "Plats traditionnels", "Plats principaux"],
  },
  {
    id: 32,
    nom: "Bouillon chaud",
    prix: "2500 FCFA",
    image: images.bouillon,
    description: "Bouillon épicé à base de viande de bœuf, servi bien chaud avec des épices locales. Disponible tout les dimanches",
    catégorie: ["Spécialitées du dimanche", "Soupes", "Plats principaux"],
    filtre: ["Spécialitées du dimanche", "Soupes", "Plats principaux"],
  },
  {
    id: 6,
    nom: "Ndolé Viande",
    prix: "3000 FCFA",
    image: images.ndolé,
    description: "Feuilles d’une plante tropicale amère mijotées avec viande et pâte d’arachide.",
    catégorie: ["Plats traditionnels", "Plats chaud", "Plats principaux"],
    filtre: ["Plats traditionnels", "Plats chaud", "Plats principaux"],
  },
  {
    id: 7,
    nom: "Saucisses grillées",
    prix: "2000 FCFA",
    image: images.saucisse,
    description: "Saucisses épicées grillées, servies chaudes.",
    catégorie: ["Grillades & Poêlés", "Plats chaud"],
    filtre: ["Grillades & Poêlés", "Plats chaud"],
  },
  {
    id: 8,
    nom: "Émincés de boeuf",
    prix: "2000 FCFA",
    image: images.émincé,
    description: "Fines lamelles de bœuf sautées, sauce légère et savoureuse.",
    catégorie: ["Plats chaud", "Plats principaux"],
    filtre: ["Plats chaud", "Plats principaux"],
  },
  {
    id: 9,
    nom: "Tripes de boeuf",
    prix: "3000 FCFA",
    image: images.tripes,
    description: "Tripes nettoyées et sautées avec condiments, texture fondante.",
    catégorie: ["Plats chaud", "Plats principaux"],
    filtre: ["Plats chaud", "Plats principaux"],
  },
  {
    id: 10,
    nom: "Rognons de boeuf",
    prix: "3500 FCFA",
    image: images.rognon,
    description: "Rognons tendres sautés à la poêle avec oignons, divers épices et piment doux.",
    catégorie: ["Plats chaud", "Plats principaux"],
    filtre: ["Plats chaud", "Plats principaux"],
  },
  {
    id: 11,
    nom: "Ndolé au poisson Fumé",
    prix: "2500 FCFA",
    image: images.ndoléFumé,
    description: "Ndolé revisité avec poisson fumée, goût intense et rustique.",
    catégorie: ["Plats chaud", "Plats traditionnels", "Plats principaux"],
    filtre: ["Plats chaud", "Plats traditionnels", "Plats principaux"],
  },
  {
    id: 12,
    nom: "Pommes sautées avec poisson",
    prix: "2500 FCFA",
    image: images.pommePoisson,
    description: "Pommes de terre sautées accompagnées de filets de poisson épicé.",
    catégorie: ["Plats chaud", "Plats principaux"],
    filtre: ["Plats chaud", "Plats principaux"],
  },
  {
    id: 13,
    nom: "Poulet Yassa",
    prix: "5000 FCFA",
    image: images.pouletYassa,
    description: "Poulet mariné aux oignons, citron et moutarde, originaire du Sénégal.",
    catégorie: ["Plats chaud", "Plats principaux"],
    filtre: ["Plats chaud", "Plats principaux"],
  },
  {
    id: 14,
    nom: "Bar Braisé",
    prix: [{label: "Moyen", value: "7000 FCFA", selected: true},
      {label: "Gros", value: "8000 FCFA"}
    ],
    image: images.barBraisé,
    description: "Filet de bar rôti à la braise, peau croustillante chaire tendre.",
    catégorie: ["Grillades & Poêlés"],
    filtre: ["Grillades & Poêlés"],
  },
  {
    id: 15,
    nom: "Bar Calada Braisé",
    prix: [{label: "Moyen", value: "5000 FCFA", selected: true},
      {label: "Gros", value: "6000 FCFA"}
    ],
    image: images.calada,
    description: "Bar calada rôti à la braise avec un mélange d'épices exotiques.",
    catégorie: ["Grillades & Poêlés"],
    filtre: ["Grillades & Poêlés"],
  },
  {
    id: 16,
    nom: "Carpe Braisé",
    prix: [{label: "Moyen", value: "4000 FCFA", selected: true},
      {label: "Gros", value: "5000 FCFA"}
    ],
    image: images.carpe,
    description: "Carpe entière grillé, parfumée aux herbes et condiments locaux.",
    catégorie: ["Grillades & Poêlés"],
    filtre: ["Grillades & Poêlés"],
  },
  {
    id: 17,
    nom: "Foie de boeuf sauté",
    prix: "3000 FCFA",
    image: images.foie,
    description: "Foie de boeuf sauté aux oignons et poivrons, tendre et parfumé.",
    catégorie: ["Plats chaud", "Plats principaux"],
    filtre: ["Plats chaud", "Plats principaux"],
  },
  {
    id: 18,
    nom: "Omelette Nature",
    prix: "1500 FCFA",
    image: images.omlette,
    description: "Omelette simple aux oeufs battus, légère et moelleuse.",
    catégorie: ["Petit déjeuné"],
    filtre: ["Petit déjeuné"],
  },
  {
    id: 19,
    nom: "Omelette Sardine",
    prix: "2000 FCFA",
    image: images.omletteSardine,
    description: "Omelette garnie de sardines et dépices douces.",
    catégorie: ["Petit déjeuné"],
    filtre: ["Petit déjeuné"],
  },
  {
    id: 20,
    nom: "Omelette Saucisson",
    prix: "2000 FCFA",
    image: images.omletteSaucisson,
    description: "Omelette généreuse au saucisson, parfaite pour les gourmands.",
    catégorie: ["Petit déjeuné"],
    filtre: ["Petit déjeuné"],
  },
  {
    id: 21,
    nom: "Tasse de lait",
    prix: "500 FCFA",
    image: images.tasse,
    description: "Lait chaud servi nature, doux et reconfortant.",
    catégorie: ["Boissons chaudes"],
    filtre: ["Boissons chaudes"],
  },
  {
    id: 22,
    nom: "Thé Citron",
    prix: "500 FCFA",
    image: images.théCitron,
    description: "Infusion légère au citron, rafraichissanté et tonifiante",
    catégorie: ["Boissons chaudes"],
    filtre: ["Boissons chaudes"],
  },
  {
    id: 23,
    nom: "Thé Menthe",
    prix: "500 FCFA",
    image: images.théMenthe,
    description: "Thé vert infusé à la menthe fraîche, apaisant et parfumé.",
    catégorie: ["Boissons chaudes"],
    filtre: ["Boissons chaudes"],
  },
  {
    id: 24,
    nom: "Thé Vert",
    prix: "500 FCFA",
    image: images.théVert,
    description: "Thé classique riche en antioxydants, goût pur et naturel.",
    catégorie: ["Boissons chaudes"],
    filtre: ["Boissons chaudes"],
  },
  {
    id: 26,
    nom: "Plantains Vapeur",
    prix: "",
    image: images.plantainVapeur,
    description: "Plantains cuit à la vapeur",
    catégorie: ["Accompagnements"],
    filtre: ["Accompagnements"],
  },
  {
    id: 27,
    nom: "Plantains Frit",
    prix: "",
    image: images.plantainFrie,
    description: "Plantains frit et dorés à l'huile.",
    catégorie: ["Accompagnements"],
    filtre: ["Accompagnements"],
  },
  {
    id: 28,
    nom: "Plantains tapé",
    prix: "",
    image: images.tapé,
    description: "Plantains écrasé et frit, croustillant et moelleux.",
    catégorie: ["Accompagnements"],
    filtre: ["Accompagnements"],
  },
  {
    id: 29,
    nom: "Frites de pommes de terres",
    prix: "",
    image: images.frite,
    description: "Pommes de terre frit et dorés à l'huile.",
    catégorie: ["Accompagnements"],
    filtre: ["Accompagnements"],
  },
  {
    id: 30,
    nom: "Pommes Vapeur",
    prix: "",
    image: images.pommeVapeur,
    description: "Pommes de terre cuit à la vapeur.",
    catégorie: ["Accompagnements"],
    filtre: ["Accompagnements"],
  },
  {
    id: 31,
    nom: "Riz Pilaf",
    prix: "",
    image: images.pilaf,
    description: "Riz parfumé mijoté et assaisonné cuit à la vapeur",
    catégorie: ["Accompagnements"],
    filtre: ["Accompagnements"],
  }
];

export const drinksItems: MenuItem[] = [
  {
    id: 129,
    nom: "Le cuivre",
    prix: "5000 FCFA",
    image: images.cuivre,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 128,
    nom: "Tour Cantelou",
    prix: "5000 FCFA",
    image: images.cantelouBlanc,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 127,
    nom: "Isabelle De France",
    prix: "6000 FCFA",
    image: images.isabelle,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 126,
    nom: "Calvet",
    prix: "6000 FCFA",
    image: images.calvetBlanc,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 125,
    nom: "Ballart De Guest",
    prix: "7000 FCFA",
    image: images.ballartrosé,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 124,
    nom: "Louis Echenauer",
    prix: "7000 FCFA",
    image: images.louisBlanc,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 123,
    nom: "Moscato",
    prix: "10,000 FCFA",
    image: images.moscato,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 122,
    nom: "Hugo Rosé",
    prix: "10,000 FCFA",
    image: images.hugo,
    catégorie: ["Vins Rosé"],
    filtre: ["Vins Rosé"],
  },
  {
    id: 121,
    nom: "Mia",
    prix: "15,000 FCFA",
    image: images.mia,
    catégorie: ["Vins Rosé"],
    filtre: ["Vins Rosé"],
  },
  {
    id: 120,
    nom: "Tour Cantelou",
    prix: "5000 FCFA",
    image: images.cantelouRouge,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 119,
    nom: "Louis Echenauer",
    prix: "8000 FCFA",
    image: images.louisRouge,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 118,
    nom: "Le Cuivre",
    prix: "5000 FCFA",
    image: images.cuivre,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 117,
    nom: "Calvet",
    prix: "5000 FCFA",
    image: images.calvet,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 116,
    nom: "Grand Antoine",
    prix: "7000 FCFA",
    image: images.antoine,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 115,
    nom: "Chatron De La Croix",
    prix: "7000 FCFA",
    image: images.chatron,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 114,
    nom: "Grand Sud Merlot",
    prix: "7000 FCFA",
    image: images.merlot,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 113,
    nom: "Shiraz Cabernet",
    prix: "7000 FCFA",
    image: images.shiraz,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 112,
    nom: "Rio Lindo",
    prix: "8000 FCFA",
    image: images.rio,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 111,
    nom: "El Castilla",
    prix: "8000 FCFA",
    image: images.castilla,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 110,
    nom: "Damati",
    prix: "10,000 FCFA",
    image: images.damati,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 109,
    nom: "Villata",
    prix: "15,000 FCFA",
    image: images.villalta,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 108,
    nom: "Chianti",
    prix: "20,000 FCFA",
    image: images.chianti,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 107,
    nom: "Charles Vincent",
    prix: "25,000 FCFA",
    image: images.vincent,
    catégorie: ["Champagnes"],
    filtre: ["Champagnes"],
  },
  {
    id: 106,
    nom: "Pata Negra",
    prix: "25,000 FCFA",
    image: images.pataNegra,
    catégorie: ["Champagnes"],
    filtre: ["Champagnes"],
  },
  {
    id: 105,
    nom: "Ruinart",
    prix: "105,000 FCFA",
    image: images.ruinart,
    catégorie: ["Champagnes"],
    filtre: ["Champagnes"],
  },
  {
    id: 104,
    nom: "Imperial Blue",
    prix: "3500 FCFA",
    image: images.imperialBlue,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 103,
    nom: "Black",
    prix: "3500 FCFA",
    image: images.black,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 102,
    nom: "Black & White",
    prix: "15,000 FCFA",
    image: images.blackWhite,
    catégorie: ["Whiskys", "Produits Guinnes"],
    filtre: ["Whiskys", "Produits Guinnes"],
  },
  {
    id: 32,
    nom: "WS",
    prix: "10,000 FCFA",
    image: images.ws,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 91,
    nom: "Yatch Club",
    prix: "10,000 FCFA",
    image: images.yatch,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 33,
    nom: "WS 1805",
    prix: "10,000 FCFA",
    image: images.w1805,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 34,
    nom: "Eperon",
    prix: "10,000 FCFA",
    image: images.eperon,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 35,
    nom: "Bagpiper",
    prix: "10,000 FCFA",
    image: images.bagpiper,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 36,
    nom: "Baileys",
    prix: "15,000 FCFA",
    image: images.baileys,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 37,
    nom: "Martini Blanc",
    prix: "15,000 FCFA",
    image: images.martiniBlanc,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 38,
    nom: "Martini Rouge",
    prix: "15,000 FCFA",
    image: images.martiniRouge,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 39,
    nom: "Jameson",
    prix: "20,000 FCFA",
    image: images.jameson,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 40,
    nom: "Red Label",
    prix: "20,000 FCFA",
    image: images.redlabel,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 41,
    nom: "Hunting Lodge",
    prix: "20,000 FCFA",
    image: images.hunting,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 42,
    nom: "Label 5",
    prix: "25,000 FCFA",
    image: images.label5,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 43,
    nom: "William Lawson's",
    prix: "25,000 FCFA",
    image: images.lawsons,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 44,
    nom: "Sir Edward's",
    prix: "25,000 FCFA",
    image: images.edwards,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 45,
    nom: "Glen Scanlan",
    prix: "25,000 FCFA",
    image: images.glen,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 46,
    nom: "Pastis 51",
    prix: "25,000 FCFA",
    image: images.pastis51,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 47,
    nom: "Black Label",
    prix: "30,000 FCFA",
    image: images.blackLabel,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 48,
    nom: "Grants",
    prix: "30,000 FCFA",
    image: images.grants,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 49,
    nom: "Chivas 12 ans",
    prix: "30,000 FCFA",
    image: images.chivas12,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 50,
    nom: "The Singleton",
    prix: "35,000 FCFA",
    image: images.singleton,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 51,
    nom: "Gold Label",
    prix: "55,000 FCFA",
    image: images.gold,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 52,
    nom: "Jack Daniel",
    prix: "55,000 FCFA",
    image: images.jack,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 53,
    nom: "Double Black",
    prix: "75,000 FCFA",
    image: images.doubleBlack,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 54,
    nom: "Gold Label",
    prix: "35,000 FCFA",
    image: images.goldLabel,
    catégorie: ["Whiskys"],
    filtre: ["Whiskys"],
  },
  {
    id: 101,
    nom: "33 export",
    prix: "1000 FCFA",
    image: images.export33,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 100,
    nom: "Kadji Beer",
    prix: "1000 FCFA",
    image: images.kadji,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 99,
    nom: "Doppel",
    prix: "1000 FCFA",
    image: images.doppel,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 55,
    nom: "Petite Guinnes",
    prix: "1000 FCFA",
    image: images.petiteGuinnes,
    catégorie: ["Produits Guinnes"],
    filtre: ["Produits Guinnes"],
  },
  {
    id: 56,
    nom: "Grande Guinnes",
    prix: "2000 FCFA",
    image: images.petiteGuinnes,
    catégorie: ["Produits Guinnes"],
    filtre: ["Produits Guinnes"],
  },
  {
    id: 57,
    nom: "Guinnes Smooth",
    prix: "1000 FCFA",
    image: images.smooth,
    catégorie: ["Produits Guinnes"],
    filtre: ["Produits Guinnes"],
  },
  {
    id: 58,
    nom: "Harp",
    prix: "1000 FCFA",
    image: images.harp,
    catégorie: ["Produits Guinnes"],
    filtre: ["Produits Guinnes"],
  },
  {
    id: 59,
    nom: "Orijin",
    prix: "1000 FCFA",
    image: images.orijin,
    catégorie: ["Produits Guinnes"],
    filtre: ["Produits Guinnes"],
  },
  {
    id: 60,
    nom: "Malta Guinnes",
    prix: "1000 FCFA",
    image: images.maltaguinnes,
    catégorie: ["Produits Guinnes"],
    filtre: ["Produits Guinnes"],
  },
  {
    id: 61,
    nom: "Mützig",
    prix: "1000 FCFA",
    image: images.mutzig,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 62,
    nom: "Beaufort",
    prix: "1000 FCFA",
    image: images.beaufort,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 63,
    nom: "Beaufort Light",
    prix: "1000 FCFA",
    image: images.light,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 64,
    nom: "Racine",
    prix: "1000 FCFA",
    image: images.racine,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 65,
    nom: "Isenback",
    prix: "1500 FCFA",
    image: images.isenbeck,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 66,
    nom: "ice",
    prix: "1000 FCFA",
    image: images.ice,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 68,
    nom: "Castel",
    prix: "1000 FCFA",
    image: images.castel,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 69,
    nom: "Chill",
    prix: "1000 FCFA",
    image: images.chill,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 70,
    nom: "Coca-Cola",
    prix: "1000 FCFA",
    image: images.coca,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 71,
    nom: "Top Grenadine",
    prix: "1000 FCFA",
    image: images.topGrenadine,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 72,
    nom: "Top Ananas",
    prix: "1000 FCFA",
    image: images.topAnanas,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 73,
    nom: "top Orange",
    prix: "1000 FCFA",
    image: images.topOrange,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 74,
    nom: "Top Pamplemousse",
    prix: "1000 FCFA",
    image: images.topPlamplemousse,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 75,
    nom: "Spécial Pamplemousse",
    prix: "1000 FCFA",
    image: images.spécilaPamplemousse,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 76,
    nom: "Djino",
    prix: "1000 FCFA",
    image: images.coca,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 77,
    nom: "Vimto",
    prix: "1000 FCFA",
    image: images.vimto,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 78,
    nom: "Orangina",
    prix: "1000 FCFA",
    image: images.orangina,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 79,
    nom: "Vanpur Vanilla",
    prix: "1000 FCFA",
    image: images.vanpurVanille,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 80,
    nom: "Vanpur Coffee",
    prix: "1000 FCFA",
    image: images.vanpurCoffee,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 81,
    nom: "Power Malt",
    prix: "1000 FCFA",
    image: images.powerMalt,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
  {
    id: 82,
    nom: "Vody",
    prix: "1000 FCFA",
    image: images.vody,
    catégorie: ["Vodka"],
    filtre: ["Vodka"],
  },
  {
    id: 83,
    nom: "3X Energy",
    prix: "1000 FCFA",
    image: images.xenergy,
    catégorie: ["Boissons Energétique"],
    filtre: ["Boissons Energétique"],
  },
  {
    id: 84,
    nom: "Frutas",
    prix: "1500 FCFA",
    image: images.frutas,
    catégorie: ["Jus Naturels"],
    filtre: ["Jus Naturels"],
  },
  {
    id: 85,
    nom: "Extra Fresco",
    prix: "1000 FCFA",
    image: images.fresco,
    catégorie: ["Jus Naturels"],
    filtre: ["Jus Naturels"],
  },
  {
    id: 86,
    nom: "Jus De Bissap (Foléré)",
    prix: "1000 FCFA",
    image: images.bissap,
    catégorie: ["Jus Naturels"],
    filtre: ["Jus Naturels"],
  },
  {
    id: 87,
    nom: "Jus De Baobab",
    prix: "1000 FCFA",
    image: images.baobab,
    catégorie: ["Jus Naturels"],
    filtre: ["Jus Naturels"],
  },
  {
    id: 88,
    nom: "El Vino",
    prix: "2000 FCFA",
    image: images.elvino,
    catégorie: ["Vins Blanc"],
    filtre: ["Vins Blanc"],
  },
  {
    id: 89,
    nom: "Heineken",
    prix: "1000 FCFA",
    image: images.heineken,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 90,
    nom: "Jus De Gingembre",
    prix: "1000 FCFA",
    image: images.ginger,
    catégorie: ["Jus Naturels"],
    filtre: ["Jus Naturels"],
  },
  {
    id: 92,
    nom: "Booster",
    prix: "1000 FCFA",
    image: images.booster,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 93,
    nom: "Ceyssac",
    prix: "10,000 FCFA",
    image: images.ceyssac,
    catégorie: ["Vins Rouge"],
    filtre: ["Vins Rouge"],
  },
  {
    id: 94,
    nom: "Bavaria",
    prix: "1000 FCFA",
    image: images.bavaria,
    catégorie: ["Bières / Brasséries"],
    filtre: ["Bières / Brasséries"],
  },
  {
    id: 95,
    nom: "Redbull",
    prix: "1500 FCFA",
    image: images.redbull,
    catégorie: ["Boissons Energétique"],
    filtre: ["Boissons Energétique"],
  },
  {
    id: 96,
    nom: "Bullet",
    prix: "1000 FCFA",
    image: images.bullet,
    catégorie: ["Vodka"],
    filtre: ["Vodka"],
  },
  {
    id: 97,
    nom: "Reaktor",
    prix: "1000 FCFA",
    image: images.reaktor,
    catégorie: ["Boissons Energétique"],
    filtre: ["Boissons Energétique"],
  },
  {
    id: 98,
    nom: "Fanta",
    prix: "1000 FCFA",
    image: images.fanta,
    catégorie: ["Boissons Gazeuse"],
    filtre: ["Boissons Gazeuse"],
  },
];

// Versions avec identifiants uniques et préfixés par type
export const menuItemsUniq: MenuItem[] = menuItems.map((item) => ({
  ...item,
  id: `P-${String(item.id)}`,
}));

export const drinksItemsUniq: MenuItem[] = drinksItems.map((item) => ({
  ...item,
  id: `B-${String(item.id)}`,
}));
